import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./app.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lotus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
        <title>Lotus</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}